baseURL = "http://127.0.0.1:1313/"
languageCode = "en-us"
title = "Testing is Fun"
theme = "bvh"
author = "Bart"
summaryLength = 50

[Menus]
  main = [
      {Name = "Blog", URL = "/blog"}
  ]

[params]
  description = "Mijn custom description"
  include_toc = true
  subtitleLength = 25
  logo = "/images/logo.png"
  pagination = 9

[params.meta]
  description = "mijn site"
  keywords = "testing, software, javascript, python"

[params.social]
  twitter = "vherckb"
  linkedin = "abc"
  github = "ikke"


[params.author]
  name = "Bart"
  thumbnail = "/images/author.jpg"
  description = "Software Tester"